/* *** Generated with Desideria SVD converter *** */
#pragma once

#include "deri/registers.h"

#include <cstdint>

namespace deri::mmio {
struct CAN_regs {
  enum class CTL_bits : uint32_t;
  enum class STAT_bits : uint32_t;
  enum class TSTAT_bits : uint32_t;
  enum class RFIFO0_bits : uint32_t;
  enum class RFIFO1_bits : uint32_t;
  enum class INTEN_bits : uint32_t;
  enum class ERR_bits : uint32_t;
  enum class BT_bits : uint32_t;
  enum class TMI0_bits : uint32_t;
  enum class TMP0_bits : uint32_t;
  enum class TMDATA00_bits : uint32_t;
  enum class TMDATA10_bits : uint32_t;
  enum class TMI1_bits : uint32_t;
  enum class TMP1_bits : uint32_t;
  enum class TMDATA01_bits : uint32_t;
  enum class TMDATA11_bits : uint32_t;
  enum class TMI2_bits : uint32_t;
  enum class TMP2_bits : uint32_t;
  enum class TMDATA02_bits : uint32_t;
  enum class TMDATA12_bits : uint32_t;
  enum class RFIFOMI0_bits : uint32_t;
  enum class RFIFOMP0_bits : uint32_t;
  enum class RFIFOMDATA00_bits : uint32_t;
  enum class RFIFOMDATA10_bits : uint32_t;
  enum class RFIFOMI1_bits : uint32_t;
  enum class RFIFOMP1_bits : uint32_t;
  enum class RFIFOMDATA01_bits : uint32_t;
  enum class RFIFOMDATA11_bits : uint32_t;
  enum class FCTL_bits : uint32_t;
  enum class FMCFG_bits : uint32_t;
  enum class FSCFG_bits : uint32_t;
  enum class FAFIFO_bits : uint32_t;
  enum class FW_bits : uint32_t;
  enum class F0DATA0_bits : uint32_t;
  enum class F0DATA1_bits : uint32_t;
  enum class F1DATA0_bits : uint32_t;
  enum class F1DATA1_bits : uint32_t;
  enum class F2DATA0_bits : uint32_t;
  enum class F2DATA1_bits : uint32_t;
  enum class F3DATA0_bits : uint32_t;
  enum class F3DATA1_bits : uint32_t;
  enum class F4DATA0_bits : uint32_t;
  enum class F4DATA1_bits : uint32_t;
  enum class F5DATA0_bits : uint32_t;
  enum class F5DATA1_bits : uint32_t;
  enum class F6DATA0_bits : uint32_t;
  enum class F6DATA1_bits : uint32_t;
  enum class F7DATA0_bits : uint32_t;
  enum class F7DATA1_bits : uint32_t;
  enum class F8DATA0_bits : uint32_t;
  enum class F8DATA1_bits : uint32_t;
  enum class F9DATA0_bits : uint32_t;
  enum class F9DATA1_bits : uint32_t;
  enum class F10DATA0_bits : uint32_t;
  enum class F10DATA1_bits : uint32_t;
  enum class F11DATA0_bits : uint32_t;
  enum class F11DATA1_bits : uint32_t;
  enum class F12DATA0_bits : uint32_t;
  enum class F12DATA1_bits : uint32_t;
  enum class F13DATA0_bits : uint32_t;
  enum class F13DATA1_bits : uint32_t;
  enum class F14DATA0_bits : uint32_t;
  enum class F14DATA1_bits : uint32_t;
  enum class F15DATA0_bits : uint32_t;
  enum class F15DATA1_bits : uint32_t;
  enum class F16DATA0_bits : uint32_t;
  enum class F16DATA1_bits : uint32_t;
  enum class F17DATA0_bits : uint32_t;
  enum class F17DATA1_bits : uint32_t;
  enum class F18DATA0_bits : uint32_t;
  enum class F18DATA1_bits : uint32_t;
  enum class F19DATA0_bits : uint32_t;
  enum class F19DATA1_bits : uint32_t;
  enum class F20DATA0_bits : uint32_t;
  enum class F20DATA1_bits : uint32_t;
  enum class F21DATA0_bits : uint32_t;
  enum class F21DATA1_bits : uint32_t;
  enum class F22DATA0_bits : uint32_t;
  enum class F22DATA1_bits : uint32_t;
  enum class F23DATA0_bits : uint32_t;
  enum class F23DATA1_bits : uint32_t;
  enum class F24DATA0_bits : uint32_t;
  enum class F24DATA1_bits : uint32_t;
  enum class F25DATA0_bits : uint32_t;
  enum class F25DATA1_bits : uint32_t;
  enum class F26DATA0_bits : uint32_t;
  enum class F26DATA1_bits : uint32_t;
  enum class F27DATA0_bits : uint32_t;
  enum class F27DATA1_bits : uint32_t;
  enum class CTL_shift : unsigned;
  enum class STAT_shift : unsigned;
  enum class TSTAT_shift : unsigned;
  enum class RFIFO0_shift : unsigned;
  enum class RFIFO1_shift : unsigned;
  enum class INTEN_shift : unsigned;
  enum class ERR_shift : unsigned;
  enum class BT_shift : unsigned;
  enum class TMI0_shift : unsigned;
  enum class TMP0_shift : unsigned;
  enum class TMDATA00_shift : unsigned;
  enum class TMDATA10_shift : unsigned;
  enum class TMI1_shift : unsigned;
  enum class TMP1_shift : unsigned;
  enum class TMDATA01_shift : unsigned;
  enum class TMDATA11_shift : unsigned;
  enum class TMI2_shift : unsigned;
  enum class TMP2_shift : unsigned;
  enum class TMDATA02_shift : unsigned;
  enum class TMDATA12_shift : unsigned;
  enum class RFIFOMI0_shift : unsigned;
  enum class RFIFOMP0_shift : unsigned;
  enum class RFIFOMDATA00_shift : unsigned;
  enum class RFIFOMDATA10_shift : unsigned;
  enum class RFIFOMI1_shift : unsigned;
  enum class RFIFOMP1_shift : unsigned;
  enum class RFIFOMDATA01_shift : unsigned;
  enum class RFIFOMDATA11_shift : unsigned;
  enum class FCTL_shift : unsigned;
  enum class FMCFG_shift : unsigned;
  enum class FSCFG_shift : unsigned;
  enum class FAFIFO_shift : unsigned;
  enum class FW_shift : unsigned;
  enum class F0DATA0_shift : unsigned;
  enum class F0DATA1_shift : unsigned;
  enum class F1DATA0_shift : unsigned;
  enum class F1DATA1_shift : unsigned;
  enum class F2DATA0_shift : unsigned;
  enum class F2DATA1_shift : unsigned;
  enum class F3DATA0_shift : unsigned;
  enum class F3DATA1_shift : unsigned;
  enum class F4DATA0_shift : unsigned;
  enum class F4DATA1_shift : unsigned;
  enum class F5DATA0_shift : unsigned;
  enum class F5DATA1_shift : unsigned;
  enum class F6DATA0_shift : unsigned;
  enum class F6DATA1_shift : unsigned;
  enum class F7DATA0_shift : unsigned;
  enum class F7DATA1_shift : unsigned;
  enum class F8DATA0_shift : unsigned;
  enum class F8DATA1_shift : unsigned;
  enum class F9DATA0_shift : unsigned;
  enum class F9DATA1_shift : unsigned;
  enum class F10DATA0_shift : unsigned;
  enum class F10DATA1_shift : unsigned;
  enum class F11DATA0_shift : unsigned;
  enum class F11DATA1_shift : unsigned;
  enum class F12DATA0_shift : unsigned;
  enum class F12DATA1_shift : unsigned;
  enum class F13DATA0_shift : unsigned;
  enum class F13DATA1_shift : unsigned;
  enum class F14DATA0_shift : unsigned;
  enum class F14DATA1_shift : unsigned;
  enum class F15DATA0_shift : unsigned;
  enum class F15DATA1_shift : unsigned;
  enum class F16DATA0_shift : unsigned;
  enum class F16DATA1_shift : unsigned;
  enum class F17DATA0_shift : unsigned;
  enum class F17DATA1_shift : unsigned;
  enum class F18DATA0_shift : unsigned;
  enum class F18DATA1_shift : unsigned;
  enum class F19DATA0_shift : unsigned;
  enum class F19DATA1_shift : unsigned;
  enum class F20DATA0_shift : unsigned;
  enum class F20DATA1_shift : unsigned;
  enum class F21DATA0_shift : unsigned;
  enum class F21DATA1_shift : unsigned;
  enum class F22DATA0_shift : unsigned;
  enum class F22DATA1_shift : unsigned;
  enum class F23DATA0_shift : unsigned;
  enum class F23DATA1_shift : unsigned;
  enum class F24DATA0_shift : unsigned;
  enum class F24DATA1_shift : unsigned;
  enum class F25DATA0_shift : unsigned;
  enum class F25DATA1_shift : unsigned;
  enum class F26DATA0_shift : unsigned;
  enum class F26DATA1_shift : unsigned;
  enum class F27DATA0_shift : unsigned;
  enum class F27DATA1_shift : unsigned;

  Register<CTL_bits> CTL;
  Register<STAT_bits> STAT;
  Register<TSTAT_bits> TSTAT;
  Register<RFIFO0_bits> RFIFO0;
  Register<RFIFO1_bits> RFIFO1;
  Register<INTEN_bits> INTEN;
  Register<ERR_bits> ERR;
  Register<BT_bits> BT;
  const Reserved<uint32_t> reserved_0[88];
  // Base + 0x180
  Register<TMI0_bits> TMI0;
  Register<TMP0_bits> TMP0;
  Register<TMDATA00_bits> TMDATA00;
  Register<TMDATA10_bits> TMDATA10;
  Register<TMI1_bits> TMI1;
  Register<TMP1_bits> TMP1;
  Register<TMDATA01_bits> TMDATA01;
  Register<TMDATA11_bits> TMDATA11;
  Register<TMI2_bits> TMI2;
  Register<TMP2_bits> TMP2;
  Register<TMDATA02_bits> TMDATA02;
  Register<TMDATA12_bits> TMDATA12;
  const Register<RFIFOMI0_bits> RFIFOMI0;
  const Register<RFIFOMP0_bits> RFIFOMP0;
  const Register<RFIFOMDATA00_bits> RFIFOMDATA00;
  const Register<RFIFOMDATA10_bits> RFIFOMDATA10;
  const Register<RFIFOMI1_bits> RFIFOMI1;
  const Register<RFIFOMP1_bits> RFIFOMP1;
  const Register<RFIFOMDATA01_bits> RFIFOMDATA01;
  const Register<RFIFOMDATA11_bits> RFIFOMDATA11;
  const Reserved<uint32_t> reserved_1[12];
  // Base + 0x200
  Register<FCTL_bits> FCTL;
  Register<FMCFG_bits> FMCFG;
  const Reserved<uint32_t> reserved_2;
  // Base + 0x20c
  Register<FSCFG_bits> FSCFG;
  const Reserved<uint32_t> reserved_3;
  // Base + 0x214
  Register<FAFIFO_bits> FAFIFO;
  const Reserved<uint32_t> reserved_4;
  // Base + 0x21c
  Register<FW_bits> FW;
  const Reserved<uint32_t> reserved_5[8];
  // Base + 0x240
  Register<F0DATA0_bits> F0DATA0;
  Register<F0DATA1_bits> F0DATA1;
  Register<F1DATA0_bits> F1DATA0;
  Register<F1DATA1_bits> F1DATA1;
  Register<F2DATA0_bits> F2DATA0;
  Register<F2DATA1_bits> F2DATA1;
  Register<F3DATA0_bits> F3DATA0;
  Register<F3DATA1_bits> F3DATA1;
  Register<F4DATA0_bits> F4DATA0;
  Register<F4DATA1_bits> F4DATA1;
  Register<F5DATA0_bits> F5DATA0;
  Register<F5DATA1_bits> F5DATA1;
  Register<F6DATA0_bits> F6DATA0;
  Register<F6DATA1_bits> F6DATA1;
  Register<F7DATA0_bits> F7DATA0;
  Register<F7DATA1_bits> F7DATA1;
  Register<F8DATA0_bits> F8DATA0;
  Register<F8DATA1_bits> F8DATA1;
  Register<F9DATA0_bits> F9DATA0;
  Register<F9DATA1_bits> F9DATA1;
  Register<F10DATA0_bits> F10DATA0;
  Register<F10DATA1_bits> F10DATA1;
  Register<F11DATA0_bits> F11DATA0;
  Register<F11DATA1_bits> F11DATA1;
  Register<F12DATA0_bits> F12DATA0;
  Register<F12DATA1_bits> F12DATA1;
  Register<F13DATA0_bits> F13DATA0;
  Register<F13DATA1_bits> F13DATA1;
  Register<F14DATA0_bits> F14DATA0;
  Register<F14DATA1_bits> F14DATA1;
  Register<F15DATA0_bits> F15DATA0;
  Register<F15DATA1_bits> F15DATA1;
  Register<F16DATA0_bits> F16DATA0;
  Register<F16DATA1_bits> F16DATA1;
  Register<F17DATA0_bits> F17DATA0;
  Register<F17DATA1_bits> F17DATA1;
  Register<F18DATA0_bits> F18DATA0;
  Register<F18DATA1_bits> F18DATA1;
  Register<F19DATA0_bits> F19DATA0;
  Register<F19DATA1_bits> F19DATA1;
  Register<F20DATA0_bits> F20DATA0;
  Register<F20DATA1_bits> F20DATA1;
  Register<F21DATA0_bits> F21DATA0;
  Register<F21DATA1_bits> F21DATA1;
  Register<F22DATA0_bits> F22DATA0;
  Register<F22DATA1_bits> F22DATA1;
  Register<F23DATA0_bits> F23DATA0;
  Register<F23DATA1_bits> F23DATA1;
  Register<F24DATA0_bits> F24DATA0;
  Register<F24DATA1_bits> F24DATA1;
  Register<F25DATA0_bits> F25DATA0;
  Register<F25DATA1_bits> F25DATA1;
  Register<F26DATA0_bits> F26DATA0;
  Register<F26DATA1_bits> F26DATA1;
  Register<F27DATA0_bits> F27DATA0;
  Register<F27DATA1_bits> F27DATA1;
};
}  // namespace deri::mmio
