if(NOT SOC_MODEL)
  message(FATAL_ERROR "Missing SOC_MODEL setting in deri_bsp.cmake")
endif()

set(ARCH riscv)
set(CPU_CORE e31)
set(CPU rv32)
set(CPU_C_FLAGS -march=rv32imac -mabi=ilp32)
set(CODE_MODEL_C_FLAGS -mcmodel=medlow)
target_compile_options(deri_soc_flags INTERFACE ${CODE_MODEL_C_FLAGS} ${CPU_C_FLAGS})
target_link_options(deri_soc_flags INTERFACE ${CPU_C_FLAGS})
set(RISCV_RAM_ORIGIN 0x80000000)
set(RISCV_RAM_LENGTH 16K)
set(RISCV_ROM_ORIGIN 0x20400000)
if (SOC_MODEL STREQUAL "qemu")
  set(RISCV_ROM_LENGTH 4M)
endif ()
target_link_libraries(deri_soc_flags INTERFACE "-T sifive-fe310-periph.ld")
