set(ARCH riscv)
set(CPU_CORE bumblebee)
set(CPU rv32)
set(CPU_MODEL gd32vf103cbt6)
set(CPU_C_FLAGS -march=rv32imac -mabi=ilp32)
set(CODE_MODEL_C_FLAGS -mcmodel=medlow)
target_compile_options(deri_bsp_flags INTERFACE ${CODE_MODEL_C_FLAGS} ${CPU_C_FLAGS})
target_link_options(deri_bsp_flags INTERFACE ${CPU_C_FLAGS} -T "${DERI_ARCH_DIR}/ld/gd32vf103cbt6.ld")
target_link_directories(deri_bsp_flags INTERFACE "${DERI_ARCH_DIR}/ld" "${DERI_ARCH_BASEDIR}/common/ld")
