set(ARCH riscv)
set(CPU_C_FLAGS -march=rv64imac -mabi=lp64)
set(CODE_MODEL_C_FLAGS -mcmodel=medany -mexplicit-relocs)
add_compile_options(${CODE_MODEL_C_FLAGS} ${CPU_C_FLAGS})
set(LINKER_SCRIPT "${CMAKE_CURRENT_SOURCE_DIR}/arch/riscv/ld/sifive_e.lds")
add_link_options(${CPU_C_FLAGS} -T ${LINKER_SCRIPT})
