set(CMAKE_CROSSCOMPILING_EMULATOR qemu-system-riscv32 -nographic -machine sifive_e -kernel)
set(ARCH riscv)
set(CPU_C_FLAGS -march=rv32imac -mabi=ilp32)
set(CODE_MODEL_C_FLAGS -mcmodel=medany -mexplicit-relocs)
add_compile_options(${CODE_MODEL_C_FLAGS} ${CPU_C_FLAGS})
set(LINKER_SCRIPT "${DERI_ARCH_BASEDIR}/riscv/ld/sifive_e.lds")
add_link_options(${CPU_C_FLAGS} -T ${LINKER_SCRIPT} -L "${DERI_ARCH_BASEDIR}/common/ld")
