set(CMAKE_CROSSCOMPILING_EMULATOR qemu-system-riscv32 -nographic -machine sifive_e -kernel)
set(ARCH riscv)
set(CPU_CORE e31)
set(CPU rv32)
set(CPU_MODEL fe310)
set(CPU_C_FLAGS -march=rv32imac -mabi=ilp32)
set(CODE_MODEL_C_FLAGS -mcmodel=medlow)
target_compile_options(deri_bsp_flags INTERFACE ${CODE_MODEL_C_FLAGS} ${CPU_C_FLAGS})
target_link_options(deri_bsp_flags INTERFACE ${CPU_C_FLAGS} -T "${DERI_BSP_BASEDIR}/${BOARD}/ld/sifive_e.lds")
target_link_directories(deri_bsp_flags INTERFACE "${DERI_BSP_BASEDIR}/${BOARD}/ld")
