set(CMAKE_CROSSCOMPILING_EMULATOR qemu-system-riscv64 -nographic -machine sifive_u,start-in-flash=on -bios none -kernel)
set(ARCH riscv)
set(CPU_CORE u54)
set(CPU rv64)
set(CPU_MODEL fu540)
set(CPU_C_FLAGS -march=rv64imac -mabi=lp64)
set(CODE_MODEL_C_FLAGS -mcmodel=medany -mexplicit-relocs)
target_compile_options(deri_bsp_flags INTERFACE ${CODE_MODEL_C_FLAGS} ${CPU_C_FLAGS})
target_link_options(deri_bsp_flags INTERFACE ${CPU_C_FLAGS} -T "${DERI_BSP_BASEDIR}/${BOARD}/ld/sifive_u.lds")
target_link_directories(deri_bsp_flags INTERFACE "${DERI_BSP_BASEDIR}/${BOARD}/ld" "${DERI_ARCH_BASEDIR}/${ARCH}/ld" "${DERI_ARCH_BASEDIR}/common/ld")
